spring.application.name=event-management-platform

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Razorpay Test Mode
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}

#Admin Details
app.seed.admin.email=${ADMIN_SEED_EMAIL:}
app.seed.admin.password=${ADMIN_SEED_PASSWORD:}
app.seed.admin.name=${ADMIN_SEED_NAME}

